### PR TITLE
Fix/enforce performance

### PR DESCRIPTION
**Pull request by rbickham11**
This implements the somewhat hacky fix we found while debugging.

**Question:** I'm not sure the standard for versioning on forks? Should I follow their versioning or start over with our own? Waiting to publish until I figure this out.

### CODE REVIEW

**Comment by MPiccinato** [comment]
@rbickham11 I am also curious how the fork versioning should work. I would assume we would maybe publish this fix to Sift's NPM area and just consume it from there for now?

**Comment by rbickham11** [comment]
@MPiccinato Yeah of course. I was more asking about what the version should be

**Comment by hsluoyz** [comment]
@nodece, can we add a new version of `EnforceSync()` for them?

**Comment by nodece** [comment]
@hsluoyz 

We can add the `EnforceSync()`.

We need to think about  async function.

If matcher has async function, the `enforce` does not provide a correct result.

**Comment by hsluoyz** [comment]
@nodece , we can add a warning in the comment.

**Comment by nodece** [comment]
@hsluoyz hahaha, good idea.

**Comment by nodece** [comment]
@hsluoyz @rbickham11 Hi, I created a PR: https://github.com/casbin/node-casbin/pull/96

**Comment by hsluoyz** [comment]
Merged.

**Pull request closed without merging**
